#feign
server:
  port: 9000
spring:
  application:
    name: feign-provider-9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
logging:
  level:
    eurekaserver8080: debug
  file:
    name: log/feign-provider-9000.log