#eureka-server
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    fetch-registry: false
    register-with-eureka: false
spring:
  application:
    name: eureka-server-8080
logging:
  level:
    eurekaserver8080: debug
  file:
    name: D:/app/document/idea_workspace/springcompent/log/eureka-server-8080.log
