#feign
#server:
#  port: 9000
spring:
  application:
    name: feign-provider-9000
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8080/eureka
logging:
  level:
    com.example.feignprovider9000: debug
  file:
    name: D:/app/document/idea_workspace/springcompent/log/feign-provider-9000.log