#feign
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testshiro?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
#  application:
#    name: feign-customer-10001
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8080/eureka
logging:
  level:
    com.example.feigncustomer10001: debug
  file:
    name: D:/app/document/idea_workspace/springcompent/log/feign-customer-10001.log
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 10001
#开启服务熔断
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 7000
        readTimeout: 7000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000
ribbon:
  MaxAutoRetries: 0 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试
  MaxAutoRetriesNextServer: 0 #切换实例的重试次数
  OkToRetryOnAllOperations: false # 对所有的操作请求都进行重试，如果是get则可以，如果是post,put等操作没有实现幂等的情况下是很危险的