#feign
server:
  port: 10001
spring:
  application:
    name: feign-customer-10001
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8080/eureka
logging:
  level:
    com.example.feigncustomer10001: debug
  file:
    name: /log/feign-customer-10001.log
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testshiro?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapper/*.xml