#feign
server:
  port: 9001
spring:
  application:
    name: feign-provider-9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
logging:
  level:
    com.example.feignprovider9001: debug
  file:
    name: /log/feign-provider-9001.log